### ISSUE TITLE
Private Server - All Names Red and Won't Let Teleport

### ISSUE THREAD

**Issue by TheIdioticOtaku** [fredtargaryen/Floocraft#29]
Hi there! I'm not sure why, but on my server when my friends and I have made floo fireplaces, the names show up but they are red and won't allow us to teleport at all. Any/All help is greatly appreciated.

**Comment by fredtargaryen** [comment]
Hi! That's really unusual...
Sorry if this comes off as patronising but you didn't clarify so I need to ask: has a fire been lit in the fireplace below the floo sign?
If so, please could you provide a copy of your world that I can investigate? Or at the very least, a picture of one of the fireplaces so I can check everything is in order?
Also which Forge version are you using?

**Comment by TheIdioticOtaku** [comment]
Yes, the fire is lit and it is green. We are using forge 14.23.5.2847. [Here is a picture of one of our fireplaces](http://prntscr.com/rjfyyk), and also the [world file/mods](https://drive.google.com/file/d/1SuXvv6N6s8vHABcmGVAkrbbZRHVqdXwH/view?usp=sharing). Thank you so much for your help!

**Comment by fredtargaryen** [comment]
Hi again,
It looks like this fireplace isn't going to work because the Floo Sign is too far away from the fire. If you are looking at the fireplace from the top down, a valid fireplace would have the Floo Sign adjacent to the fire along the x or z axis.
As it is currently, that Floo Sign is looking for a fire block on top of that cobblestone block you have placed in front of the green fire. That plus no surrounding walls means the fireplace will always be invalid.
This is an interesting fireplace design though and I might consider variable depth fireplaces in the future.

**Comment by TheIdioticOtaku** [comment]
Thank you so much for the help! We have resolved the issue by fixing the fireplaces and can now travel faster! I love the mod, and look forward to any future updates! :D
