### ISSUE TITLE
Sometimes the destination fire does not turn into floo fire

### ISSUE THREAD

**Issue by Compaszer** [fredtargaryen/Floocraft#42]
This does happen from time to time causing you to burn alive as you come out of the destination fireplace.

**Comment by fredtargaryen** [comment]
Hi! This one is tricky because what you've described sounds like intended gameplay.
If your destination fire had not been converted into Floo fire, it stays green (or blue) for about a second after you arrive, giving you a short window to get out of the fireplace.
If your destination fire had already been converted to Floo fire before you arrived there, it will be green (or blue) when you arrive, and stay that way so that you can use it to teleport elsewhere.

Does that match up with the experience you're having? If not then we have a bug on our hands.

**Comment by Compaszer** [comment]
Hi,
it's almost as you've described. I've tested it further and found out, that
the destination fire indeed turns into floo fire for a short period of
time, but unfortunately that's way to short to get out. The fire is already
red again when I get out of the flash animation. I don't know if this is
intended.

James Curran ***@***.***> schrieb am Fr., 20. Aug. 2021,
15:13:

**Comment by fredtargaryen** [comment]
Oops, I actually deleted that comment thinking I had misread what you wrote. I'll have a look at the timing again, and lengthen it if it seems short to me, as well as make it a configuration setting.

**Comment by Compaszer** [comment]
Thanks a lot, a configurable time would be awesome :D

James Curran ***@***.***> schrieb am Fr., 20. Aug. 2021,
22:04:

**Comment by fredtargaryen** [comment]
OK, it is pretty unforgiving especially if latency is high.
I've bumped the default time from 30 ticks (1.5 seconds) to 50 ticks (2.5 seconds), and let you configure the time between 1 and 100 ticks (0.05 to 5 seconds). Easier to escape but still a little urgent. Commit coming soon; release coming less soon as there are more things I want to add.

Thanks for reporting!

**Comment by fredtargaryen** [comment]
The first release that fixes this issue is now available [here](https://www.curseforge.com/minecraft/mc-mods/floocraft/files/3433415). The relevant commit is 80155e2ca30b98e96d33187fb0e12076bf83b99c.

**Comment by Compaszer** [comment]
Thank you so much for your fast response and fix, I really appreciate it :D
